### ISSUE TITLE
Why are `cachify_without_agents` and `cachify_without_ids` textareas?

### ISSUE THREAD

**Issue by krafit** [pluginkollektiv/cachify#120]
![bildschirmfoto 2017-07-03 um 17 04 56](https://user-images.githubusercontent.com/1038789/27798943-92ca93da-6013-11e7-8bb8-d5e7d21b177c.png)
Pre 2.3 these fields were simple `<input>` elements, with decent padding and perfect alignment with their respective labels. 

![bildschirmfoto 2017-07-03 um 17 04 42](https://user-images.githubusercontent.com/1038789/27798942-929df7b2-6013-11e7-9e26-cf9e456bed09.png)
In #53 they where replaced by textareas, causing misalignment and some strange behavior, if content overflows the initial size of the container. 
Yes textareas _might_ provide better UX for the edgecase of overflowing input fields. But users often don't realize, they can actually resize them. 

So we are potentially sacrificing elegance for a theoretical problem (overflowing input fields) - I'm not aware of a single question in the support forums caused by this problem. 

I'd suggest to partially revert this change and ship `2.3.0` without it. UX/UI/a11y is a key field of work for `2.4.0` anyway.

I really like the placeholders though.

**Comment by stklcode** [comment]
> some strange behavior, if content overflows the initial size of the container

Despite that, a user might actually enter line-separated values intentionally, which are sanitized to blanks, not commas (there is no explicit notice that blanks are not supported). Leads to a potential misunderstanding that an input with one ID per line leads to no ID excluded at all (because the actual ID is compared agaings something like `1 2 3`). 

So if multiline-input should be enabled, it should be either not sanitized and newline added to the custom `_preg_split()` or sanitized to commas instead of blanks (e.g. replace `sanitize_text_field($input)` with something like`str_replace(array("\r\n","\r","\n"), ',', sanitize_textarea_field($input))`).


I'm with @krafit to revert this at current state, because long input is not readable any better without manual resizing, but causing potential trouble at other places.
