### ISSUE TITLE
Are Sabai Directory Listings cached?

### ISSUE THREAD

**Issue by klettersteige** [pluginkollektiv/cachify#149]
I use the plugin [Sabai Directory](https://codecanyon.net/item/sabai-directory-plugin-for-wordpress/4505485) and it seems that cachify does not cache these listings.
I have a very long "time to first byte" for my "sabai listings".
You can see the difference in this analysis
https://tools.pingdom.com/#!/eqlZJD/http://www.via-ferrata.de/kletterroute-eisenzeit-vom-riffelriss-auf-die-zugspitze/ (normal Wordpress Post)
https://tools.pingdom.com/#!/d6B0Wd/http://www.via-ferrata.de/touren/gps/zugspitze-eisenzeit-iv (Sabai Post Listing) 
how can I use cachify for the sabai listings? Can you please help me!

**Comment by chesio** [comment]
Hi, it's hard to tell what the issue exactly is, because Sabai Directory is a premium plugin. But I noticed that the Sabai Post Listing URL returns "no cache" headers in response:
```
Cache-Control:no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma:no-cache
```

On the other hand, normal WP post returns:
```
Cache-Control:max-age=600
```

So maybe the Sabai Directory plugin turns off caching in some way - for example Cachify will skip caching, if ```DONOTCACHEPAGE``` constant is true.

**Comment by stklcode** [comment]
As far as I assume it holds that Sabai pages cannot be cached safely by Cachify, because the plugin stores information off the WP page structure and hence other plugins like Cachify won't detect updates to invalidate the cache and hence will show outdated content and manually clearing the cache is probably against the idea behind a listing plugin.

There are probably some workarounds utilizing some hooks to achieve that, but I don't have any particular experience with this combination.

In general one might consider alternative techniques like reverse proxy caching with more or less short TTL depending on the actual page load and number of requests which the might outperform Cachify anyway in some situations (yet requires server level configuration capabilities, so not always suitable)

**Comment by websupporter** [comment]
Hi @klettersteige,
I am closing this for now. If you have further questions, feel free to reopen the issue.

Thank you.
