### ISSUE TITLE
Is there any webp feature planned?

### ISSUE THREAD

**Issue by albi** [pluginkollektiv/cachify#163]
like cache enabler, which generates a gzipped html version with webp images instead of jpg/png images. generating these webp images is no problem, but caching a proper version of the WordPress output is.

**Comment by Zodiac1978** [comment]
Not planned at the moment. But happily considering. :)

May I ask why you don't use Cache Enabler (it is a fork of Cachify and seems to support this like you wrote)?

**Comment by krafit** [comment]
I actually tend to disagree with @Zodiac1978 on this one.

In my option WebP generation should be handled by a another plugin, not your _caching plugin_, because... well it's not really _caching_ related.

But I'd opt for an addition to our documentation to maybe give a recommendation how to solve this.

**Comment by albi** [comment]
The webp image generation is handled by EWWW Image Optimizer. Cache Enabler from KeyCDN only adds an option to generate gzipped html pages where jpg is replaced by webp file formats. With the htaccess additions the right version is served by the apache server..

**Comment by krafit** [comment]
Ah I see, thanks for the clarification.
I'll put in on the roadmap for an upcoming version, sound like something a bit tricky but worthwhile.

**Comment by derweili** [comment]
@albi using webp with cachify is already possible. You don't need to generate a separate html file.
You can use the existing plugin which includes jpg and png files.

You can then add some rewrite rules to your .htaccess files, so instead of jpg/png files your server returns webp images if avialable and supported by the browser.

Code for your .htaccess file:

```
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{HTTP_ACCEPT} image/webp
    RewriteCond %{DOCUMENT_ROOT}/$1.webp -f
    RewriteRule ^(wp-content/uploads.+)\.(jpe?g|png)$ $1.webp
[T=image/webp,E=accept:1]

</IfModule>
<IfModule mod_headers.c>
    Header append Vary Accept env=REDIRECT_accept
</IfModule>
AddType image/webp .webp
```

Code for nginx configuration
```
# http config block
map $http_accept $webp_ext {
default "";
"~*webp" ".webp";
}
# server config block
location ~* ^/wp-content/.+\.(png|jpg)$ {
add_header Vary Accept;
try_files $uri$webp_ext $uri =404;
```

So when a JPG/PNG image is requested by the browser, the server checks if image/webp is included in the accept headers.
If no the JPG/PNG file is served.
If so, the server checks if a webp image avialable. (The webp image must be named as the jpg/png file, just with a different file extension).
If so, the webp image is send to client. If not the JPG/PNG file is sent.


Based on this solution I think there is no need for generating separate HTML files.

What are the advantages of generating special webp html files instead of using the described .htaccess solution?

**Comment by albi** [comment]
Hi Julian,

thanks so far for your help. Will try this on my next project. Cache Enabler does generate separate files for this, maybe because of less redirects? Only one redirect to the appropriate html with webp images.

Alex

**Comment by nosilver4u** [comment]
Hi all, just stumbled across this, and wanted to try and answer @derweili 's question:
"What are the advantages of generating special webp html files instead of using the described .htaccess solution?"

Using the .htaccess method (which we have available in EWWW Image Optimizer) works well if your site is not behind a caching proxy or pull-mode CDN. But, if your site IS behind a cache/proxy system, most notably Cloudflare, and a few other CDNs, one runs into trouble with those systems caching whichever file is requested first (WebP vs JPG/PNG), and then blindly delivering that to ALL your visitors.
In such a case, you need to actually alter the URLs depending on if the browser supports WebP or not (the .htaccess method is "transparent" without any URL alteration on the images). By storing both a WebP version of a page AND a non-WebP version, Cache Enabler is able to deliver the proper page to each visitor, without mixing up the two and accidentally breaking images for non-WebP browsers.

**Comment by derweili** [comment]
Hi @nosilver4u, I think this is correct for the use case when the images are offloaded on a CDN while the page itself is still running on our own server. If we have a separate webp cache file, the htaccess could route to this version and the images would load correctly.

But there are also other use cases, like delivering the whole website using a CDN. In this case we would have the same "problem", the CDN delivers the cached page version which is requested first. So the CDN needs to know about the different handling of request based on the accept headers. But this is indeed possible by correctly configuring the CDN. At least Amazons Cloudfront has this feature (I'm not familiar with Cloudflare but i guess they have a similar feature). The cache behavior can be configured to forward specific HTTP headers.
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/header-caching.html
Cloudfront then has a separat cache for different accept headers.

I'm not a pro in configuring CDN, so maybe this is not a best practice. But this is how I would solve this problem.

**Comment by stklcode** [comment]
There are always two (or three) points at which you can tweak CDN interactions. The no-brainer like enable and forget is definitely a server side solution, generated by the caching plugin. Keeping in mind that enabling a CDN is done easily today, we should not assume the average site admin to have any detailed knowledge in how the different stages do their work and what is the specific impact. (we do see this every day in the support forums for various plugin “problems“)

The same problem appears for various plugins that modify the DOM depending on certain conditions (I remember for example search engine exclusion for _Statify_ that was cached if requested first).

The given workarounds are feasible for certain scenarios and do their job. However if we want to stay with the idea of a _simple_ caching plugin and want to support WebP (“no“ is a legitimate answer here), I would be +1 for a dedicated plugin feature.
