### ISSUE TITLE
HDD-Cache on Multisite: Whole Network cleared after changing a page

### ISSUE THREAD

**Issue by V-H** [pluginkollektiv/cachify#168]
Well, I see the related issues #23 and have also seen #134. But the problem isn’t solved yet?

I'm logged in as Superadmin and working on a page of a network-site. After storing this page the directory /cachify in /wp-content/cache is gone. Also as Superadmin I want that just the cache of the site I'm working on is getting cleared. 
WP 5.1.1 Multisite, Cachify 2.4.4 (activated in network), PHP 7.2.15

**Comment by derweili** [comment]
I tested it and confirm this bug:

The Bug "only" occurs when the cache of the main site is cleared.
In this case, the cache is cleared for all sites.

Clearing the cache of a sub-site won't clear the cache of other sites.
Clearing the cache of the main-site clears the cache of all sites.

I tried it with a subdirectory-multisite. I also changed one of the sites to a different domain and the bug still occurs.

I did not test it with a multisite originally set up with subdomains.

**Comment by Zodiac1978** [comment]
The PR says
> If you click in the network admin on flush all files get deleted.
> If you click on a blog on flush, it checkes, whether the file belongs to the blog or not. If not, it won't get deleted.

After reading the comment in the source code I would say this is a bug and not the intended behaviour.
https://github.com/pluginkollektiv/cachify/blob/master/inc/cachify_hdd.class.php#L394-L408

Can you have a look @websupporter ?

**Comment by derweili** [comment]
@Zodiac1978 you are right about the PR.

I've been trying to find the reason for the bug.

Before deleting a file or directory the `Cachify_HDD::_user_can_delete()` method checks if the current file or directory is part of a site other than the currently active one. If so, it returns false which prevents the deletion of the file or folder.

This works well when clearing the cache for a sub-site.

This does not work well when clearing the cache of the main-site. 
In this case cachify tries to delete the root folder of the current (main) site, which is not part of another site the `_user_can_delete` returns `true`. 
But since it is the parent of all other sites, the cache for those sites get deleted, too.

In this case, it tries to delete the root folder of the current (main) site, which is not part of another page, but the parent folder of another page. Because of this, the cache for the other sites is also cleared.

To solve this bug we need to check if we are trying to delete the root folder of the main site.
In this case the `Cachify_HDD::_user_can_delete()` method needs to return false.
