### ISSUE TITLE
Raise required WordPress and PHP version

### ISSUE THREAD

**Issue by pfefferle** [pluginkollektiv/cachify#259]
WordPress needs at least PHP version 5.6.20+ (but recommends 7.4), so I would recommend to raise the required PHP version of cachify to 5.6 (and the required WordPress version accordingly).

-- https://wordpress.org/about/requirements/

**Comment by stklcode** [comment]
+1 for not sticking to legacy PHP.

Your suggestion for a reasonable minimum WP version? We currently support down to 4.4.
REST API stuff (like #257) requires 4.7 anyway.

PHP 5.6 is required since WP 5.2. Older releases are backwards compatible to PHP 5.2
We can raise the requirements independently, personally I'd be fine with 5.6/4.7 (but don't have requirements for anything below WP 5.8)

**Comment by florianbrinkmann** [comment]
Oh, I thought the REST API was in core since 4.4 because `register_rest_route` was introduced there, but you are right, it was 4.7.

How would we raise the versions? Add a note to a release that we will raise it in the next release, so people with older versions are informed about it, or just raise it from one version to the other?

**Comment by krafit** [comment]
My 2 cents: I'd raise to 5.6/4.7 in 2.4.0.
It's safe to assume, users with super old PHP / WP versions don't update their plugins regularly.

**Comment by stklcode** [comment]
I didn’t check the code, maybe our route is already working with 4.4. We only need a very small fraction of the API features. Officially it’s 4.7.

If you are running such version not just because yo don’t care about the site, there are usually reasons for that like major customizations that cannot be simply adjusted and designed to live until the core is EOL (3.7 received security updates, so it could still be used for site core). Plugin updates, if any, usually require manual inspection anyway in that case.

**Comment by florianbrinkmann** [comment]
@angelocali and I just tried #257 with 4.4 and it worked (except a missing dashicon)
