### ISSUE TITLE
General UI Optimizations

### ISSUE THREAD

**Issue by swissspidy** [pluginkollektiv/cachify#32]
Let's improve the accessibility and the overall UI of the plugin for a better UX.

Related: #30

**Comment by timse201** [comment]
Think it would be nice to add:
- faq in the footer besides documentation or replace it because it is german only. the faq can be translated on translate.wordpress.org and the link can be changed there to the specific language page.
- add the current cache size also to the settings page
- inform the user that saving these settings will flush the cache
- add placeholders ( #53 )
- variable boxes ( #53 )
