### ISSUE TITLE
Properly use `wp_add_inline_style()`for the admin bar icon styling

### ISSUE THREAD

**Issue by swissspidy** [pluginkollektiv/cachify#39]
Currently the plugin prints out the CSS directly, which isn't that nice.

See: https://github.com/pluginkollektiv/cachify/blob/9132770ba5102bf2eba0ec41a0b453d5106fa9f2/inc/cachify.class.php#L708

See also #38.

**Comment by visionlike** [comment]
I have testet with my changes and it works exactly in Frontend and Backend. With Valid HTML, which isn't that nice?

**Comment by swissspidy** [comment]
Thanks again for opening the _PR_ as suggested by @2ndkauboy. I only closed it because it should have been an _issue_ instead.

Anyway, we'll look into it and perhaps even change it. At the same time I think it's not that big of a deal. Your visitors aren't going to see it, so their HTML will be totally valid. I also outlined my other concerns on #38.

**Comment by visionlike** [comment]
I just wanted to help to keep it technically correct. I thought nothing of it. My Visitors are Web Developer, my Website is a sign. The Visitors can login to exchange and Work, that's all. But is ok, I do not care. I use it simply with my adaptation, the modification cost me no Minute.

I wish a pleasant evening.

**Comment by Zodiac1978** [comment]
Same problem with these lines:
https://github.com/pluginkollektiv/cachify/blob/9132770ba5102bf2eba0ec41a0b453d5106fa9f2/inc/cachify.class.php#L1695-L1700

And the use of `valign` should be changed too:
https://github.com/pluginkollektiv/cachify/blob/9132770ba5102bf2eba0ec41a0b453d5106fa9f2/inc/cachify.class.php#L1713 (and more)

**Comment by websupporter** [comment]
`valign` can be replaced without any problem. The vertical-align is already set from the WP stylesheet.

admin-bar: Since its a one liner, I think ( I guess we all agree ), it should be inline and not as a css file. I had a look. The thing is (dat ding is) WP prints out the adminbar styles as well (see `_admin_bar_bump_cb()` and how it is hooked into `wp_head`). So I can't find a proper handle to hook the `wp_add_inline_style()` in. So what would be the preferred way, if we do not have a handle?

With the inline on the options page. All it does is it sets the height of the input fields to 30px. The WP style is 28px. Haven't seen a dramatic change by just deleting the declarations and would suggest to do so.

Can prepare a PR, if someone could give me a hint with the admin_bar styles.

Thank you.

**Comment by timse201** [comment]
Possibly helpful [WP Custom Admin Bar](https://wordpress.org/plugins/wp-custom-admin-bar/)

**Comment by Zodiac1978** [comment]
Could we use this way?
https://css-tricks.com/snippets/wordpress/apply-custom-css-to-admin-area/
Used this here too:
http://torstenlandsiedel.de/2016/05/29/php-version-im-backend-anzeigen-lassen/

**Comment by bueltge** [comment]
The first way print a static css typo inside the side, not possible to minify or pack in in one css file, less of request. Why we should add the style via inline style, I can't see the benefits?

**Comment by websupporter** [comment]
Ok, my personal opinion, as I read this now again. I would vote for `wont-fix` or at least to put it out of scope for 2.3.0.

Some things have been adjusted like `valign` and except for purist reasons (a style declaration in a div is not valid html) i do not see a huge benefit right now.
