### ISSUE TITLE
nginx: [emerg] unknown directive

### ISSUE THREAD

**Issue by summerjob** [pluginkollektiv/cachify#5]
I'm trying to use memcached on my nginx server:
The option Memcached is available within the plugin but it doesn't matter what I do I always get this error message when I add your code to my config:
`nginx: [emerg] unknown directive "﻿" in /etc/nginx/sites-enabled/wordpress:52`

Here's my original config: http://pastebin.com/4D5j6BU2
and my modified (bad) config: http://pastebin.com/F6S0fMxX  (incl. FQDN modification)

What did I do wrong?

**Comment by swissspidy** [comment]
Hey there

This question is better suited for the plugin support forums on WordPress.org, if at all.

It appears that your new config has some invisible EOL characters in it (on line 50, to be precise). This usually happens when copy pasting text. There's nothing wrong with the configuration itself.

You can fix this be replacing lines 48-69 with this (just to be safe):

```
## INDEX LOCATION
location / {
    error_page 404 405 = @nocache;

    if ( $query_string ) {
        return 405;
    }
    if ( $request_method = POST ) {
        return 405;
    }
    if ( $request_uri ~ "/wp-" ) {
        return 405;
    }
    if ( $http_cookie ~ (wp-postpass|wordpress_logged_in|comment_author)_ ) {
        return 405;
    }

    default_type text/html;
    add_header X-Powered-By Cachify;
    set $memcached_key $http_host$uri;
    memcached_pass localhost:11211;
}
```

I know, you won't see any difference.

You can read more about this error message on [Stack Overflow](http://stackoverflow.com/questions/19165976/nginx-emerg-unknown-directive-in-etc-nginx-sites-enabled-example-com3) with additional tips.

**Comment by summerjob** [comment]
Thanks a lot for getting back to me this fast with a solution.
I'm sorry for bothering you with this non-existent error, can't believe this was it.
Either way, thanks a lot swissspidy!
