### ISSUE TITLE
ignore sitemap plugins - hdd cache only

### ISSUE THREAD

**Issue by timse201** [pluginkollektiv/cachify#60]
plugins like [Google XML Sitemaps](https://wordpress.org/plugins/google-sitemap-generator/) should be excluded from caching.

such plugins are very popular

the generated pages are getting cached but if you hit them there is no cache output (due to limitation in permalink). the cache will get re-generated everytime you hit these sitemaps which is very useless.

url structure:
/sitemap.xml
/sitemap-externals.xml
/sitemap-pt-post-    year-month.xml
/sitemap-pt-page-     year-month.xml

**Comment by chesio** [comment]
Simple solution for XML sitemaps is to extend "set subdirectory" in _.htaccess_ ruleset with:
```
RewriteCond %{REQUEST_URI} \.xml$
RewriteRule .* - [E=CACHIFY_DIR:%{REQUEST_URI}/]
```

Of course, this doesn't solve the problem in general, but since we expect familiarity with _.htaccess_ from anyone using HDD cache, maybe the solution is to just point plugin users to a proper documentation on the matter..?

Btw. I noticed that XML files are served with wrong content-type when fetched from HDD cache (text/html instead of text/xml or application/xml), but maybe this can be fixed via _.htaccess_ too...

**Comment by chesio** [comment]
How to avoid creation of cache files for Google XML Sitemaps:

```php
add_action('parse_query', function ($wp_query) {
    if(!empty($wp_query->query_vars["xml_sitemap"])) {
        $wp_query->is_404 = false;
        $wp_query->is_feed = true;
    }
}, 10, 1);
```

Note: This is exactly what [Google XML Sitemaps does itself](https://plugins.trac.wordpress.org/browser/google-sitemap-generator/trunk/sitemap-loader.php#L191), but unfortunately it does it too late for Cachify to notice (in `template_redirect` action). Anyway, `parse_query` action seems like more appropriate hook for such manipulation.

**Comment by blocoder** [comment]
How to exclude Google XML Sitemaps from caching with hook `cachify_skip_cache`:
```
/*
 * Cachify: Do note cache Google XML Sitemaps
 */
if (defined('CACHIFY_FILE')) {
    add_filter(
        'cachify_skip_cache',
            function() {
                global $wp_query;
                    return !empty($wp_query->query_vars["xml_sitemap"]);
                }
        );
}
```
